name: courier_chat_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # --- RUTAS Y NAVEGACIÓN ---
  go_router: ^13.2.0
  
  # --- MAPAS Y UBICACIÓN ---
  geolocator: ^13.0.0
  google_maps_flutter: ^2.10.0
  url_launcher: ^6.3.0
  
  # --- FIREBASE ---
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4
  
  # --- ALMACENAMIENTO LOCAL ---
  shared_preferences: ^2.5.3
  
  # --- SEGUNDO PLANO Y PERMISOS ---
  flutter_background_service: ^5.0.5
  flutter_local_notifications: ^17.2.2
  permission_handler: ^11.3.1
  
  # --- UTILIDADES ---
  connectivity_plus: ^6.0.0
  http: ^1.2.2
  app_links: ^3.5.0
  intl: ^0.20.2
  image_picker: ^1.1.2

  # --- UI ---
  cupertino_icons: ^1.0.8
  device_info_plus: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


# --- AQUÍ ES DONDE DEBEN IR LOS ASSETS ---
flutter:
  uses-material-design: true