// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // CONFIGURACIÓN PARA ANDROID (Corregida con tu JSON)
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyPlWMbu9TR_5XJ2McxkrDe78Rb7ohTuo', 
    appId: '1:177136918870:android:9efab5f0147804887c36f7', 
    messagingSenderId: '177136918870',
    projectId: 'dinsides-chat',
    storageBucket: 'dinsides-chat.firebasestorage.app',
  );

  // CONFIGURACIÓN PARA IOS (Usando Web como fallback temporal)
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjWh0IF7Rz5UzylTU-0hpPtYNboy11Ejc',
    appId: '1:177136918870:web:766994ddb2516b457c36f7', 
    messagingSenderId: '177136918870',
    projectId: 'dinsides-chat',
    storageBucket: 'dinsides-chat.appspot.com',
    iosBundleId: 'com.dinsides.chat', 
  );

  // CONFIGURACIÓN PARA WEB
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyDjWh0IF7Rz5UzylTU-0hpPtYNboy11Ejc",
    authDomain: "dinsides-chat.firebaseapp.com",
    projectId: "dinsides-chat",
    storageBucket: "dinsides-chat.appspot.com",
    messagingSenderId: "177136918870",
    appId: "1:177136918870:web:766994ddb2516b457c36f7",
  );
}